**Name: Taanya Nigam Roll no.:37**

Importing

In [2]:
import numpy as np

# 1. Array Creation Techniques


In [3]:
print("1. Array Creation Techniques")

1. Array Creation Techniques


a. Creating an array from a list

In [4]:
array_from_list = np.array([1, 2, 3, 4, 5])
array_from_list

array([1, 2, 3, 4, 5])

b. Using arange()

In [5]:
array_arange = np.arange(0, 10, 2)
array_arange

array([0, 2, 4, 6, 8])

c. Using linespace()

In [6]:
array_linspace = np.linspace(0, 10, 5)  # Divides 0 to 10 into 5 points
array_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

d. Using zeros()

In [7]:
array_zeros = np.zeros((3, 3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

e. Using ones()

In [8]:
array_ones = np.ones((2, 2))
array_ones

array([[1., 1.],
       [1., 1.]])

f. Using eye() for identity matrix

In [9]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 g. Using random() for random values

In [10]:
array_random = np.random.random((3, 3))
array_random

array([[0.06604885, 0.24175453, 0.60777303],
       [0.72688025, 0.64040702, 0.74483667],
       [0.26168279, 0.30573265, 0.56187023]])

# 2. Different NumPy Methods

In [11]:
print("\n2. NumPy Methods")


2. NumPy Methods


 a. Reshaping an array

In [12]:
reshaped_array = np.arange(1, 10).reshape(3, 3)
reshaped_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 b. Transposing an array

In [13]:
transposed_array = reshaped_array.T
transposed_array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

c. Mathematical operations

In [14]:
array_math = np.array([1, 2, 3])
array_math + 2
array_math * 3
np.sqrt(array_math)


array([1.        , 1.41421356, 1.73205081])

d. Aggregation methods

In [15]:
np.sum(array_math)
np.mean(array_math)
np.max(array_math)
np.min(array_math)


np.int64(1)

e. Concatenation of arrays

In [16]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
concat_array = np.concatenate((array_a, array_b))
concat_array

array([1, 2, 3, 4, 5, 6])

f. Sorting an array

In [17]:
unsorted_array = np.array([3, 1, 4, 2])
sorted_array = np.sort(unsorted_array)
sorted_array

array([1, 2, 3, 4])

 g. Indexing and Slicing

In [18]:
indexed_value = array_math[1]  # Indexing
indexed_value
sliced_array = array_math[1:3]  # Slicing
sliced_array

array([2, 3])

 h. Boolean Masking

In [19]:
boolean_mask = array_math > 2
boolean_mask
array_math[boolean_mask]

array([3])